//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/disk_image_type.proto

//go:build !protoopaque

package publicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for DiskImage resources.
type DiskImageState int32

const (
	// State is unknown or has not been determined yet.
	DiskImageState_DISK_IMAGE_STATE_UNSPECIFIED DiskImageState = 0
	// The disk image is active and available for use.
	DiskImageState_DISK_IMAGE_STATE_ACTIVE DiskImageState = 1
)

// Enum value maps for DiskImageState.
var (
	DiskImageState_name = map[int32]string{
		0: "DISK_IMAGE_STATE_UNSPECIFIED",
		1: "DISK_IMAGE_STATE_ACTIVE",
	}
	DiskImageState_value = map[string]int32{
		"DISK_IMAGE_STATE_UNSPECIFIED": 0,
		"DISK_IMAGE_STATE_ACTIVE":      1,
	}
)

func (x DiskImageState) Enum() *DiskImageState {
	p := new(DiskImageState)
	*p = x
	return p
}

func (x DiskImageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiskImageState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_disk_image_type_proto_enumTypes[0].Descriptor()
}

func (DiskImageState) Type() protoreflect.EnumType {
	return &file_osac_public_v1_disk_image_type_proto_enumTypes[0]
}

func (x DiskImageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a disk image in the OSAC platform.
//
// DiskImage is a catalog resource that defines an OS image available for provisioning compute
// instances. Users can list available disk images to select one when creating instances.
//
// buf:lint:ignore OSAC_OBJECT_SHAPE
type DiskImage struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the disk image.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the disk image.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired configuration of the disk image.
	Spec *DiskImageSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current operational status of the disk image.
	Status        *DiskImageStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskImage) Reset() {
	*x = DiskImage{}
	mi := &file_osac_public_v1_disk_image_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskImage) ProtoMessage() {}

func (x *DiskImage) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_disk_image_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiskImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiskImage) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DiskImage) GetSpec() *DiskImageSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DiskImage) GetStatus() *DiskImageStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DiskImage) SetId(v string) {
	x.Id = v
}

func (x *DiskImage) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *DiskImage) SetSpec(v *DiskImageSpec) {
	x.Spec = v
}

func (x *DiskImage) SetStatus(v *DiskImageStatus) {
	x.Status = v
}

func (x *DiskImage) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *DiskImage) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *DiskImage) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *DiskImage) ClearMetadata() {
	x.Metadata = nil
}

func (x *DiskImage) ClearSpec() {
	x.Spec = nil
}

func (x *DiskImage) ClearStatus() {
	x.Status = nil
}

type DiskImage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the disk image.
	Id string
	// Metadata of the disk image.
	Metadata *Metadata
	// Desired configuration of the disk image.
	Spec *DiskImageSpec
	// Current operational status of the disk image.
	Status *DiskImageStatus
}

func (b0 DiskImage_builder) Build() *DiskImage {
	m0 := &DiskImage{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// Defines the configuration for a DiskImage.
type DiskImageSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Human-readable description of the disk image.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// CPU architectures supported by this disk image.
	Architectures []Architecture `protobuf:"varint,2,rep,packed,name=architectures,proto3,enum=osac.public.v1.Architecture" json:"architectures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskImageSpec) Reset() {
	*x = DiskImageSpec{}
	mi := &file_osac_public_v1_disk_image_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskImageSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskImageSpec) ProtoMessage() {}

func (x *DiskImageSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_disk_image_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiskImageSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DiskImageSpec) GetArchitectures() []Architecture {
	if x != nil {
		return x.Architectures
	}
	return nil
}

func (x *DiskImageSpec) SetDescription(v string) {
	x.Description = v
}

func (x *DiskImageSpec) SetArchitectures(v []Architecture) {
	x.Architectures = v
}

type DiskImageSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Human-readable description of the disk image.
	Description string
	// CPU architectures supported by this disk image.
	Architectures []Architecture
}

func (b0 DiskImageSpec_builder) Build() *DiskImageSpec {
	m0 := &DiskImageSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Description = b.Description
	x.Architectures = b.Architectures
	return m0
}

// Represents the current operational state of a DiskImage.
type DiskImageStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current lifecycle state of the disk image.
	State         DiskImageState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.public.v1.DiskImageState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskImageStatus) Reset() {
	*x = DiskImageStatus{}
	mi := &file_osac_public_v1_disk_image_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskImageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskImageStatus) ProtoMessage() {}

func (x *DiskImageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_disk_image_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiskImageStatus) GetState() DiskImageState {
	if x != nil {
		return x.State
	}
	return DiskImageState_DISK_IMAGE_STATE_UNSPECIFIED
}

func (x *DiskImageStatus) SetState(v DiskImageState) {
	x.State = v
}

type DiskImageStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the disk image.
	State DiskImageState
}

func (b0 DiskImageStatus_builder) Build() *DiskImageStatus {
	m0 := &DiskImageStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	return m0
}

var File_osac_public_v1_disk_image_type_proto protoreflect.FileDescriptor

var file_osac_public_v1_disk_image_type_proto_rawDesc = string([]byte{
	0x0a, 0x24, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x1a, 0x26, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22,
	0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xbd, 0x01, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x34, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x75, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0d, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0d, 0x61, 0x72, 0x63, 0x68,
	0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x0f, 0x44, 0x69, 0x73,
	0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x34, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73,
	0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2a, 0x4f, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x1c, 0x44, 0x49, 0x53, 0x4b, 0x5f, 0x49, 0x4d, 0x41,
	0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x49, 0x53, 0x4b, 0x5f, 0x49,
	0x4d, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56,
	0x45, 0x10, 0x01, 0x42, 0xd6, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x42, 0x12, 0x44, 0x69, 0x73, 0x6b,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61,
	0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e, 0x4f, 0x73, 0x61, 0x63, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63,
	0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b, 0x4f, 0x73,
	0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63,
	0x3a, 0x3a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_public_v1_disk_image_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_public_v1_disk_image_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_public_v1_disk_image_type_proto_goTypes = []any{
	(DiskImageState)(0),     // 0: osac.public.v1.DiskImageState
	(*DiskImage)(nil),       // 1: osac.public.v1.DiskImage
	(*DiskImageSpec)(nil),   // 2: osac.public.v1.DiskImageSpec
	(*DiskImageStatus)(nil), // 3: osac.public.v1.DiskImageStatus
	(*Metadata)(nil),        // 4: osac.public.v1.Metadata
	(Architecture)(0),       // 5: osac.public.v1.Architecture
}
var file_osac_public_v1_disk_image_type_proto_depIdxs = []int32{
	4, // 0: osac.public.v1.DiskImage.metadata:type_name -> osac.public.v1.Metadata
	2, // 1: osac.public.v1.DiskImage.spec:type_name -> osac.public.v1.DiskImageSpec
	3, // 2: osac.public.v1.DiskImage.status:type_name -> osac.public.v1.DiskImageStatus
	5, // 3: osac.public.v1.DiskImageSpec.architectures:type_name -> osac.public.v1.Architecture
	0, // 4: osac.public.v1.DiskImageStatus.state:type_name -> osac.public.v1.DiskImageState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_public_v1_disk_image_type_proto_init() }
func file_osac_public_v1_disk_image_type_proto_init() {
	if File_osac_public_v1_disk_image_type_proto != nil {
		return
	}
	file_osac_public_v1_architecture_type_proto_init()
	file_osac_public_v1_metadata_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_disk_image_type_proto_rawDesc), len(file_osac_public_v1_disk_image_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_public_v1_disk_image_type_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_disk_image_type_proto_depIdxs,
		EnumInfos:         file_osac_public_v1_disk_image_type_proto_enumTypes,
		MessageInfos:      file_osac_public_v1_disk_image_type_proto_msgTypes,
	}.Build()
	File_osac_public_v1_disk_image_type_proto = out.File
	file_osac_public_v1_disk_image_type_proto_goTypes = nil
	file_osac_public_v1_disk_image_type_proto_depIdxs = nil
}
